import Head from "next/head"
import Image from "next/image"
import { MainLayout } from "../layouts/mainlayout"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <MainLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>Home Page</h1>
      </div>
    </MainLayout>
  )
}
